### ISSUE TITLE
The training speed of pervasive attention model

### ISSUE THREAD

**Issue by papar22** [elbayadm/attn2d#17]
Hello,

I am trying to run the pervasive attention model recipes as recommended in the README:
https://github.com/elbayadm/attn2d/blob/master/examples/pervasive/README.md

Based on my observation, the model is too slow with almost 30 words per second on a single GPU 1080! May you please give me a rough idea of what should be the speed expectations based on your experiments?

Thanks for your insights
Parnia

**Comment by elbayadm** [comment]
Hi Parnia,

When training on a single GPU (a Titan XP), the speed is approximately 880 wps.
In this log excerpt I'm training with a batch size of 348 tokens and I accumulate the gradients from 23 passes.

`| epoch 016 | valid on 'valid' subset | loss 4.701 | nll_loss 3.093 | ppl 8.53 | num_updates 9760 | best_loss 4.70069
| epoch 017 | loss 4.686 | nll_loss 3.066 | ppl 8.38 | wps 883 | ups 0 | wpb 5895.925 | bsz 261.884 | num_updates 10370 | lr 0.000310535 | gnorm 0.585 | clip 0.000 | oom 0.000 | wall 60939 | train_wall 68947
| WARNING: 21 samples have invalid sizes and will be skipped, max_positions=(100, 100), first few sample ids=[5046, 4961, 1344, 1190, 6924, 371, 4174, 4044, 6636, 6746]
`

I do aim for 8K tokens per update (max-tokens * update-freq * distributed-world-size) and try to adapt the batch size to my resources.
The max-source-positions and max-target-positions parameters can also help reduce the memory load and speed up the training. In the recommended recipe, those are set to 100 tokens and that works well with the previously described batching settings. You can lower them down and that would help at the cost of a worse accuracy (NLL or BLEU).

In any ways, 30 wps is extremely slow. Try these tweaks and let me know if they help.

Best,
Maha
