### ISSUE TITLE
AttributeError: 'float' object has no attribute 'data' on pytorch 0.4.1

### ISSUE THREAD

**Issue by adriangrepo** [elbayadm/attn2d#8]
I get the following error at trainer.backward_step() on running the demo script: 
  File "attn2d/nmt/trainer.py", line 230, in backward_step
    self.clip_norm).data.item()
AttributeError: 'float' object has no attribute 'data'

which I fixed by: 
`grad_norm = torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.clip_norm)`

Which then runs OK for torch==0.4.1

Which version of pytorch was the code written for?

**Comment by elbayadm** [comment]
The code is written for PyTorch 0.4.0.
Your fix works fine for 0.4.0 as well. 
Thanks.
